export default ([
    {intro: "The Best Cooling Pillow if You've Tried Everything and Nothing Works",
      title: 'LOFE Organic Buckwheat Pillow for Sleeping - 16" x 22" - Adjustable Loft',
      description: "Buckwheat hull pillows can be a revelation. They are the best option if you have tried everything else and nothing has worked. Beware, they are very firm. So they are not for everyone. But if they're comfortable to you, no modern technology is going to be cooler. They just doesn't get hot in the way pretty much all other pillows will once you start sweating.  The rest of the pillows below are for people who are looking for a pillow that is more like what they are used to, but that is also cooling.",
      link: "https://amzn.to/48UilXj"},
    {intro: "The Best Cooling Pillow For People Who Like Shredded Foam Pillows",
      title: "Sleep On Latex - Natural Shredded Latex Pillow",
      description: "Latex is an amazing material. Unfortunately it's also a fairly expensive one. That's because it's actually natural. It's made from the sap of the rubber tree. It's also a very springy material, which means that it can provide a lot of support. Shredded memory foam pillows are some of the best pillows for people who need a taller, more supportive pillow than down or down alternative can provide. But, to many, memory foam feals like sleeping indside a sauna. Latex won't have this problem. These pillows are a bit more affordable than other shredded latex ones because they come in a pack of two.",
      link: "https://amzn.to/3YJqxow"},
    {intro: "The Best Cooling Pillow if You Like Solid Foam Pillows",
      title: "RejuveNite American Talalay Latex - Medium Support Bed Pillow",
      description: "We prefer shredded latex becuase non-shredded latex can be a bit too firm. But if you like firm pillows, this a gread option. It won't make you sweat like a traditional solid memory foam pillow will.",
      link: "https://amzn.to/3OaZNZn"},
    {intro: "The Best Cooling Pillow if You Like Solid Foam But Aren't a Fan of Latex",
      title: "Tempur-Pedic TEMPUR-Cloud Dual Cooling Pillow - Queen",
      description: "Not everyone likes the springiness of latex. If you're one of those people, you might have to go with a more traditional opition. Tempur-pedic has been making good, but expensive pillows for ages. Somehow, their memory foam manages to be more supportive than everyone else's. Tempur-Pedic is actually one of the few brands than has figured out how to make a cooling pillow cover that works more often than not. But it's still just a cover over a hot pillow. This pillow is a bit different. It has an internal gel layer meant to prevent the heat from building up to begin with.",
      link: "https://amzn.to/3YUEhNo"},
    {intro: "The Best Cooling Pillow At A Reasonable Price",
      title: "SensorPEDIC Therapedic® Polar Nights™ - 20X Cooling Standard Memory Foam Pillow",
      description: "Unfortunately, a lot of the pillows mentioned above have been on the pricier side. That's not true of this pillow, which relies on a proprietary cooling technology. Honestly, it's hard to take the scientific claims about these products seriously. The companies change the name of the technology every year or two. But this is a model that has been around for a little while and manages to not get to hot when you've been on it for more than a few seconds.",
      link: "https://amzn.to/4fvBBwN"},
    {intro: "An Alternative Reasonably Priced Cooling Pillow",
      title: "Bedsure Breescape Cooling Pillow for Sleeping - Firm",
      description: "If your looking for a reasonably priced cooling pillow, but the firmness of buckwheat hulls doesn't work for you and the propriety foam blends don't really help, this option with a gel layer might be the best option for you. The gel layer here won't keep you cool for ever, but it lasts much longer than cooling pillow covers.",
      link: "https://amzn.to/40NtpU8"},
    ]);
