export default ([
    {intro: "The Best Memory Foam Pillow For Most People",
      title: 'UTTU Cervical Pillow for Neck Strain Relief, Memory Foam Neck Pillow for Sleeping',
      description: "Because memory foam in more dense than down or down alternative, it condenses less as you sleep on it. This makes it more necessary to get the proper height right to begin with. Sometimes people have to go through a bunch of different pillows before they get the height, hardness, and curve below the neck correct.Getting an adjustable memory foam pillow is a good way to avoid this process. This is a good afforable option that is a good starting out point for most people.",
      link: "https://amzn.to/48UilXj"},
    {intro: "The Best Memory Foam Pillow For People Who Have More To Spend",
      title: "Casper Sleep Foam Pillow, Standard",
      description: "One of the problems in the pillow market is that it can be really hard to distinguish between materials, especially when those materials have similar names. Sometimes, the namebrand pillow and the knockoff are made of similar materials. Sometimes they aren't. That's why it can pay to try leveling up. This is a foam pillow that really does feel like it is made with a better quality foam. The difference isn't enormous, but it is there.",
      link: "https://amzn.to/3YJqxow"},
    {intro: "The Best Affordable Memory Foam Pillow",
      title: "AM AEROMAX Firm Contour Memory Foam Pillow, Cervical Pillow for Neck Pain Relief",
      description: "Another way to get adjustability without using multiple pieces of foam is to make a pillow that has a higher side and a lower side. Fortunately, this is one of the designes - the contour pillow - that helps relieve neck pain. You still might find yourself needing the part of the pillow you use to be a bit lower or a bit higher, but this is a good starting point.",
      link: "https://amzn.to/3OaZNZn"},
    {intro: "The Best Memory Foam Pillow For People Who Sleep Hot",
      title: "Comfort Revolution Blue Bubble Gel + Memory Foam Pillow, Standard",
      description: "Not everyone likes the springiness of latex. If you're one of those people, you might have to go with a more traditional opition. Tempur-pedic has been making good, but expensive pillows for ages. Somehow, their memory foam manages to be more supportive than everyone else's. Tempur-Pedic is actually one of the few brands than has figured out how to make a cooling pillow cover that works more often than not. But it's still just a cover over a hot pillow. This pillow is a bit different. It has an internal gel layer meant to prevent the heat from building up to begin with.",
      link: "https://amzn.to/3YUEhNo"},
      {intro: "The Best Memory Foam Pillow For People With Neck Pain",
        title: "DONAMA Cervical Pillow for Neck and Shoulder",
        description: "If your looking for a reasonably priced cooling pillow, but the firmness of buckwheat hulls doesn't work for you and the propriety foam blends don't really help, this option with a gel layer might be the best option for you. The gel layer here won't keep you cool for ever, but it lasts much longer than cooling pillow covers.",
        link: "https://amzn.to/40NtpU8"},
      {intro: "The Best Memory Foam Pillow For People Who Sleep Hot and Have Neck Pain",
        title: "Eucior Gel Cooling Cervical Neck Pillow",
        description: "Not everyone likes the springiness of latex. If you're one of those people, you might have to go with a more traditional opition. Tempur-pedic has been making good, but expensive pillows for ages. Somehow, their memory foam manages to be more supportive than everyone else's. Tempur-Pedic is actually one of the few brands than has figured out how to make a cooling pillow cover that works more often than not. But it's still just a cover over a hot pillow. This pillow is a bit different. It has an internal gel layer meant to prevent the heat from building up to begin with.",
        link: "https://amzn.to/3YUEhNo"},
      {intro: "The Best Memory Foam Pillow For People Who Need A Thin Pillow",
        title: "LOFE Adjustable Thin Memory Foam Pillow",
        description: "If your looking for a reasonably priced cooling pillow, but the firmness of buckwheat hulls doesn't work for you and the propriety foam blends don't really help, this option with a gel layer might be the best option for you. The gel layer here won't keep you cool for ever, but it lasts much longer than cooling pillow covers.",
        link: "https://amzn.to/40NtpU8"},
      {intro: "Alternative Best Memory Foam Pillow For People Who Need A Thin Pillow",
            title: "USlixury Adjustable Side Sleeper Pillow",
            description: "If your looking for a reasonably priced cooling pillow, but the firmness of buckwheat hulls doesn't work for you and the propriety foam blends don't really help, this option with a gel layer might be the best option for you. The gel layer here won't keep you cool for ever, but it lasts much longer than cooling pillow covers.",
            link: "https://amzn.to/40NtpU8"}
    ]);
